In [143]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M")
processor = CLIPProcessor.from_pretrained("wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M")

# url = "http://images.cocodataset.org/val2017/000000039769.jpg"
# image = Image.open(requests.get(url, stream=True).raw)

# inputs = processor(text=["a photo of a cat", "a photo of a dog"], images=image, return_tensors="pt", padding=True)

# outputs = model(**inputs)
# logits_per_image = outputs.logits_per_image # this is the image-text similarity score
# probs = logits_per_image.softmax(dim=1) # we can take the softmax to get the label probabilities
# print(probs)

# total_params = sum(p.numel() for p in model.parameters())
# param_size = 4

# print(total_params /100000)
# total_size = total_params * param_size / (1024 * 1024)
# print(f'Model size in memory: {total_size:.2f} MB')

In [136]:
processor

CLIPProcessor:
- image_processor: CLIPImageProcessor {
  "crop_size": {
    "height": 224,
    "width": 224
  },
  "do_center_crop": true,
  "do_convert_rgb": true,
  "do_normalize": true,
  "do_rescale": true,
  "do_resize": true,
  "image_mean": [
    0.48145466,
    0.4578275,
    0.40821073
  ],
  "image_processor_type": "CLIPImageProcessor",
  "image_std": [
    0.26862954,
    0.26130258,
    0.27577711
  ],
  "resample": 3,
  "rescale_factor": 0.00392156862745098,
  "size": {
    "shortest_edge": 224
  }
}

- tokenizer: CLIPTokenizerFast(name_or_path='wkcn/TinyCLIP-ViT-8M-16-Text-3M-YFCC15M', vocab_size=49408, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|startoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	49406: AddedToken("<|startoftext|>", rstrip=False, lstrip=False,

In [145]:
import os
import torch


# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged") ]

images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged" , filename) 
for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged") ]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/ed2e9e4c-ec0e-437d-a13d-5a1b87340c44_20240911181755971334_20240911181756999046_0_merged_140332" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/ed2e9e4c-ec0e-437d-a13d-5a1b87340c44_20240911181755971334_20240911181756999046_0_merged_140332") if filename.startswith("0_")]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/9aa3bbb8-9cc2-48a9-a2a6-aa9c86acf71b_20240911182617744144_20240911182619026111_0_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/9aa3bbb8-9cc2-48a9-a2a6-aa9c86acf71b_20240911182617744144_20240911182619026111_0_merged") if filename.startswith("0_")]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/b2045fbc-5af3-4b40-a166-072b90f803e5_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/b2045fbc-5af3-4b40-a166-072b90f803e5_merged") if filename.startswith("0_")]

images = sorted(images, key=lambda x: int(os.path.splitext(os.path.basename(x))[0].split('_')[1]))

# images = [os.path.join("/home/ajeet/codework/datasets/Cellphone_train/train" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/Cellphone_train/train")]
# images = images[:5000]

for image in images:
    frame_path = image
    image = Image.open(image)
    # image = image.resize((224, 224))
    # inputs = processor(text=["a cell phone is not present", "a cell phone is present"], images=image, return_tensors="pt", padding=True)
    # inputs = processor(text=["absent: a cell phone", "present: a cell phone"], images=image, return_tensors="pt", padding=True)
    inputs = processor(text=["no cell phone", "a cell phone"], images=image, return_tensors="pt", padding=True)
    # inputs = processor(text=["a person", "a cell phone"], images=image, return_tensors="pt", padding=True)

    with torch.no_grad():
        outputs = model(**inputs)
    logits_per_image = outputs.logits_per_image
    probs = logits_per_image.softmax(dim=1)
    if probs[0][1] > probs[0][0]:
        print(f"{frame_path} True {probs}")
    else:
        print(f"{frame_path} False {probs}")
    # break

/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_1.jpg True tensor([[0.3873, 0.6127]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_2.jpg True tensor([[0.3806, 0.6194]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_3.jpg True tensor([[0.3880, 0.6120]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_4.jpg True tensor([[0.3823, 0.6177]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_5.jpg True tensor([[0.3782, 0.6218]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_6.jpg True tensor([[0.3884, 0.6116]])
/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged/0_7.jpg True tensor([[0.3913, 0.6087]])
/home/ajeet/codework/datasets/video_incidents_aj

In [152]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel, CLIPImageProcessor

clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# clip_processor["do_center_crop"] = False

# class CustomCLIPImageProcessor(CLIPImageProcessor):
#     def __init__(self, **kwargs):
#         super().__init__(**kwargs)
#         self.do_center_crop = False  # Disable center cropping

# # Initialize the custom processor
# clip_processor = CustomCLIPImageProcessor.from_pretrained("openai/clip-vit-base-patch16")

clip_model = clip_model.to(torch.bfloat16)

In [153]:
model_size_in_bytes = sum(p.numel() * p.element_size() for p in clip_model.parameters())
model_size_in_mb = model_size_in_bytes / (1024 ** 2)
print(f"Model size: {model_size_in_mb} MB")

Model size: 288.53857612609863 MB


In [154]:
images = [os.path.join("/home/ajeet/codework/datasets/Cellphone_train/train" , filename) 
for filename in os.listdir("/home/ajeet/codework/datasets/Cellphone_train/train")]
images = images[:1000]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged") ]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/9d47d182-296b-47d3-a64f-d6a2fd06f9f3_merged") ]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/ed2e9e4c-ec0e-437d-a13d-5a1b87340c44_20240911181755971334_20240911181756999046_0_merged_140332" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/ed2e9e4c-ec0e-437d-a13d-5a1b87340c44_20240911181755971334_20240911181756999046_0_merged_140332") if filename.startswith("0_")]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/9aa3bbb8-9cc2-48a9-a2a6-aa9c86acf71b_20240911182617744144_20240911182619026111_0_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/9aa3bbb8-9cc2-48a9-a2a6-aa9c86acf71b_20240911182617744144_20240911182619026111_0_merged") if filename.startswith("0_")]

# images = [os.path.join("/home/ajeet/codework/datasets/video_incidents_ajeet/b2045fbc-5af3-4b40-a166-072b90f803e5_merged" , filename) 
# for filename in os.listdir("/home/ajeet/codework/datasets/video_incidents_ajeet/b2045fbc-5af3-4b40-a166-072b90f803e5_merged") if filename.startswith("0_")]

# images = sorted(images, key=lambda x: int(os.path.splitext(os.path.basename(x))[0].split('_')[1]))

for image in images:
    frame_path = image
    image = Image.open(image)
    image = image.resize((224, 224))  # Resize to the expected input size
    # inputs = clip_processor(text=["a cell phone not visible", "a cell phone visible"], images=image, return_tensors="pt", padding=True)
    # inputs = clip_processor(text=["no cell phone", "a cell phone"], images=image, return_tensors="pt", padding=True)
    inputs = processor(text=["a person", "a cell phone"], images=image, return_tensors="pt", padding=True)

    with torch.no_grad():
        outputs = clip_model(**inputs)
    logits_per_image = outputs.logits_per_image
    probs = logits_per_image.softmax(dim=1)
    if probs[0][1] > probs[0][0]:
        print(f"{frame_path} True {probs}")
    else:
        print(f"{frame_path} False {probs}")

/home/ajeet/codework/datasets/Cellphone_train/train/25499.jpg True tensor([[0.0420, 0.9570]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/23416.jpg True tensor([[0.2451, 0.7539]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/100445_2020-07-23_10850__mob_poison.jpg True tensor([[0.0374, 0.9609]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/25857_mob_poison.jpg True tensor([[0.2949, 0.7070]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/24578_mob_poison.jpg True tensor([[0.0674, 0.9336]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/97553_2020-07-21_3647__mob_jitter.jpg True tensor([[0.2227, 0.7773]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/44248_2020-04-14_9219__mob_jitter.jpg False tensor([[0.8945, 0.1069]], dtype=torch.bfloat16)
/home/ajeet/codework/datasets/Cellphone_train/train/25930_mob_jitter.jpg True t

KeyboardInterrupt: 

In [155]:
import torch

print("CPU float16 support:", torch.backends.mps.is_available() if torch.backends.mps.is_available() else "No")


CPU float16 support: No


In [74]:
# # Store image embeddings
image_embeddings = []

for image_path in images:
    image = Image.open(image_path)
    inputs = clip_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        image_features = clip_model.get_image_features(**inputs)
    image_embeddings.append((image_path, image_features))

print("Image embeddings calculated and stored.")

# def get_image_embeddings(frames, batch_size=500):
#     embeddings_list = []
#     for i in range(0, len(frames), batch_size):
#         batch_frames = frames[i:i + batch_size]
#         images = [Image.open(frame) for frame in batch_frames]
        
#         with torch.no_grad():
#             inputs = clip_processor(images=images, return_tensors="pt")
#             input_memory = inputs['pixel_values'].element_size() * inputs['pixel_values'].nelement()
#             print(f"Memory taken by input tensor: {input_memory / (1024 ** 2):.2f} MB")
            
#             embeddings = clip_model.get_image_features(**inputs)
        
#         # Normalize the embeddings in the batch
#         embeddings = embeddings / embeddings.norm(dim=1, keepdim=True)
#         embeddings_list.append(embeddings)
    
#     # Concatenate all normalized embeddings into a single tensor
#     return torch.cat(embeddings_list)
# image_embeddings = get_image_embeddings(images)

Image embeddings calculated and stored.


In [ ]:
def get_text_embedding(query):
    # inputs = self.processor(text=query, return_tensors="pt", padding=True).to(self.device)
    inputs = clip_processor(text=query, return_tensors="pt")
    with torch.no_grad():
        text_embedding = clip_processor.get_text_features(**inputs)
    text_embedding = text_embedding / text_embedding.norm(dim=1, keepdim=True)
    return text_embedding

In [77]:
# Define multiple sets of queries
queries = [
    ["a cell phone not present", "a cell phone present"],
    # ["a person", "a cell phone"],
    # Add more queries if needed
]

# for query_set in queries:
#     # Process the text queries
#     text_inputs = clip_processor(text=query_set, return_tensors="pt", padding=True)
#     with torch.no_grad():
#         text_features = clip_model.get_text_features(**text_inputs)

#     # text_features = text_features / text_features.norm(dim=-1, keepdim=True)

    
#     for image_path, image_embedding in zip(images, image_embeddings):
#         # Calculate logits and probabilities using stored image features and text features
#         logits_per_image = (image_embedding @ text_features.T).squeeze(0)
#         print(logits_per_image)
#         probs = logits_per_image.softmax(dim=0)
        
#         # Assuming the second label (index 1) corresponds to the positive case (e.g., cell phone present)
#         if probs[1] > probs[0]:
#             print(f"{image_path} True {probs}")
#         else:
#             print(f"{image_path} False {probs}")


for query_set in queries:
    # Process the text queries
    text_inputs = clip_processor(text=query_set, return_tensors="pt", padding=True)
    with torch.no_grad():
        text_features = clip_model.get_text_features(**text_inputs)
    
    for image_path, image_embedding in image_embeddings:
        # Calculate logits and probabilities using stored image features and text features
        logits_per_image = (image_embedding @ text_features.T).squeeze(0)
        print(logits_per_image)
        probs = logits_per_image.softmax(dim=0)
        
        # Assuming the second label (index 1) corresponds to the positive case (e.g., cell phone present)
        if probs[1] > probs[0]:
            print(f"{image_path} True {probs}")
        else:
            print(f"{image_path} False {probs}")

tensor([27.6109, 23.7261])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_1.jpg False tensor([0.9799, 0.0201])
tensor([27.8784, 24.0094])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_2.jpg False tensor([0.9795, 0.0205])
tensor([24.3097, 21.1763])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_3.jpg False tensor([0.9582, 0.0418])
tensor([25.9242, 22.5491])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_4.jpg False tensor([0.9669, 0.0331])
tensor([26.4685, 22.8479])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_5.jpg False tensor([0.9739, 0.0261])
tensor([26.1726, 22.2424])
/home/ajeet/codework/datasets/video_incidents_ajeet/f044cf1d-8a5b-4703-a05c-3b57c5c14989_merged/0_6.jpg False tensor([0.9807, 0.0193])
tensor([26.3591, 22.5335])
/